# Grasps the object with the given object_frame_id.

# goal
uint8 FREE=0 # Given orientation is used
uint8 FRONT=1 #Orientation is calculated from robot orientation
uint8 TOP=2 #Orientation is calculated from robot orientation

string object_frame_id #tf_frame == knowrob_object_id
geometry_msgs/PoseStamped goal_pose # in map
geometry_msgs/Vector3 object_size
uint8 grasp_mode
---
# result
uint8 SUCCESS=0
uint8 FAILED=1

uint8 error_code
---
# feedback
geometry_msgs/TransformStamped tf_gripper_to_object
float64 gripper_joint_state
