# Moves robot into perceiving position:

# goal
uint8 TABLE_BIG=0 
uint8 TABLE_SMALL=1 
uint8 SHELF1=2 
uint8 SHELF2=3 
uint8 perceive_mode
---
# result
uint8 SUCCESS=0
uint8 FAILED=1
uint8 error_code
---
# feedback
float64 torso_joint_state
