# Places the object in the gripper down at the given pose.
# goal
uint8 FREE=0 # Given orientation is used
uint8 FRONT=1 #Orientation is calculated from robot orientation
uint8 TOP=2 #Orientation is calculated from robot orientation

string object_frame_id
geometry_msgs/PoseStamped goal_pose # pose in map Position of hand_palm_link
uint8 place_mode
---
# result
uint8 SUCCESS=0
uint8 FAILED=1

uint8 error_code
---
# feedback
geometry_msgs/TransformStamped tf_object_to_goal # object-pose in goal_frame
float64 gripper_joint_state
