# Moves robot into perceiving position:

# goal
uint8 NEUTRAL=0
uint8 LOOK_LOW=1
uint8 LOOK_HIGH=2
uint8 GAZE=3
uint8 pose_mode
geometry_msgs/Vector3 gaze_point
---
# result
uint8 SUCCESS=0
uint8 FAILED=1
uint8 error_code
---
# feedback
float64 torso_joint_state
