# Moves robot into perceiving position:

# goal
uint8 FREE=0
uint8 NEUTRAL=1
uint8 LOOK_LOW=2
uint8 LOOK_HIGH=3
uint8 LOOK_FLOOR = 4
uint8 GAZE=5

uint8 pose_mode
geometry_msgs/Vector3 gaze_point

float32 head_pan_joint
float32 head_tilt_joint
float32 arm_lift_joint
float32 arm_flex_joint
float32 arm_roll_joint
float32 wrist_flex_joint
float32 wrist_roll_joint
---
# result
uint8 SUCCESS=0
uint8 FAILED=1
uint8 error_code
---
# feedback
float64 torso_joint_state
