# Moves the gripper to the given pose
# define the goal
geometry_msgs/PoseStamped goal_pose # pose in map
---
# define the result
uint8 SUCCESS = 0
uint8 FAILED = 1

uint8 error_code
---
# define feedback
geometry_msgs/TransformStamped tf_gripper_to_goal #object pose in goal frame