# opens the object with the given object_frame_id.
# goal

string object_name #tf_frame of door == knowrob_object_id
string object_link_name #tf_frame of handle == knowrob_object_id
float32 angle_goal # the target anggle goal
---
# result
uint8 SUCCESS=0
uint8 FAILED=1

uint8 error_code
---
# feedback
#TODO